[workspace]
resolver = "2"
members = [
    "crates/pyval-core",
    "wrappers/python",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/aibrushcomputer/pyval"
